name: Metrics
on:
  schedule: 
  - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: wopian/metrics@75f202b4b24bcbe6a2f69a58e195d7239e0708d7
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: wopian
          base: ''
          config_timezone: Europe/London
          plugin_traffic: yes
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_languages_colors: github
          # plugin_languages_ignored: ${{ vars.EXCLUDED_LANGS }}
          plugin_languages_skipped: ${{ vars.EXCLUDED_REPOS }}
          # plugin_languages_sections: most-used, recently-used
          plugin_languages_sections: recently-used
          plugin_languages_indepth: yes
          plugin_languages_indepth_custom: zeepkist/zeepkist, zeepkist/combine, zeepkist/gtr-client
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_recent_load: 10000
          plugin_languages_recent_days: 14
          plugin_languages_other: no
          # plugin_followup: yes
          # plugin_followup_indepth: yes
          # plugin_followup_archived: no
          plugin_achievements: no
          plugin_notable: yes
          # plugin_notable_from: all
          plugin_notable_indepth: yes
          # plugin_notable_types: commit, pull_request
          optimize: svg
          experimental_features: --optimize-svg
