name: Metrics
on:
  schedule: 
  - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: wopian/metrics@dd64c50bf38be91795e73980f3483d028e7e55ee
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: wopian
          base: community, repositories, metadata, repository, repositories
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_traffic: yes
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15
          plugin_languages_other: yes
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_archived: no
          plugin_achievements: yes
          plugin_achievements_limit: 5
          plugin_achievements_ignored: >-
            polyglot, stargazer, deployer, member, worker, forker, gister, follower, inspirer, chatter, helper, automater, infographile, octonaut
          optimize: svg
          experimental_features: --optimize-svg
