name: Metrics
on:
  schedule: 
  - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: wopian/metrics@dd64c50bf38be91795e73980f3483d028e7e55ee
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.achievements.svg
          base: ""
          plugin_achievements: yes

      - uses: wopian/metrics@dd64c50bf38be91795e73980f3483d028e7e55ee
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.base.svg
          base: header, activity, community, repositories, metadata
          
      - uses: wopian/metrics@dd64c50bf38be91795e73980f3483d028e7e55ee
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.followup.indepth.svg
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_archived: no
          
      - uses: wopian/metrics@dd64c50bf38be91795e73980f3483d028e7e55ee
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.languages.details.svg
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
          
      - uses: wopian/metrics@dd64c50bf38be91795e73980f3483d028e7e55ee
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.languages.recent.svg
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_sections: recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
          
      - uses: wopian/metrics@dd64c50bf38be91795e73980f3483d028e7e55ee
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.languages.indepth.svg
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15
          
      - uses: wopian/metrics@dd64c50bf38be91795e73980f3483d028e7e55ee
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.licenses.ratio.svg
          base: ""
          template: repository
          repo: metrics
          plugin_licenses: yes
          plugin_licenses_setup: bash -c '[[ -f package.json ]] && npm ci || true'
          plugin_licenses_legal: no
          plugin_licenses_ratio: yes
          
      - uses: wopian/metrics@dd64c50bf38be91795e73980f3483d028e7e55ee
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.notable.indepth.svg
          base: ""
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          
      - uses: wopian/metrics@dd64c50bf38be91795e73980f3483d028e7e55ee
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.traffic.svg
          base: repositories
          plugin_traffic: yes
